python -u fine_tuning.py \
  --task_name "classification" \
  --dataset_name "FaceDetection" \
  --data "UEA" \
  --root_path "./datasets/FaceDetection" \
  --forward_layers 1 \
  --conv1d True \
  --out_channels 32 \
  --stride 4 \
  --batch_size 8 \
  --learning_rate 0.00025 \
  --num_workers 0 \
  --lradj "type2" \
