python -u fine_tuning.py \
  --task_name "classification" \
  --dataset_name "SelfRegulationSCP2" \
  --data "UEA" \
  --root_path "./datasets/SelfRegulationSCP2" \
  --forward_layers 2 \
  --conv1d True \
  --out_channels 32 \
  --stride 16 \
  --batch_size 4 \
  --learning_rate 0.0008 \
  --num_workers 0 \
  --lradj "type1" \
