python -u fine_tuning.py \
  --task_name "classification" \
  --dataset_name "Heartbeat" \
  --data "UEA" \
  --root_path "./datasets/Heartbeat" \
  --forward_layers 3 \
  --conv1d True \
  --out_channels 18 \
  --stride 4 \
  --batch_size 16 \
  --learning_rate 0.00025 \
  --num_workers 0 \
  --lradj "type1" \
