python -u fine_tuning.py \
  --task_name "classification" \
  --dataset_name "JapaneseVowels" \
  --data "UEA" \
  --root_path "./datasets/JapaneseVowels" \
  --forward_layers 1 \
  --conv1d False \
  --out_channels 32 \
  --stride 4 \
  --batch_size 32 \
  --learning_rate 0.002 \
  --num_workers 0 \
  --lradj "cosine" \
